"""social accounts

Revision ID: 83183979a20c
Revises: a7cfcfe408de
Create Date: 2026-01-01 14:48:29.710701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83183979a20c'
down_revision: Union[str, None] = 'a7cfcfe408de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_provider_user_id'),
    sa.UniqueConstraint('provider', 'user_id', name='uq_provider_user_id')
    )
    op.create_index(op.f('ix_social_accounts_provider'), 'social_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_social_accounts_provider_user_id'), 'social_accounts', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_provider_user_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_provider'), table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
